# Load prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt correct_all
unsetopt correct

for config_file ($HOME/.config/zsh/*.zsh) source $config_file
